"use client";

import {
  File,
  Folder,
  FolderOpen,
  FileCode,
  FileJson,
  FileText,
  Image,
  Settings,
  GitBranch,
  Search,
  Terminal,
  MessageSquare,
  Play,
  X,
  Plus,
  Minus,
  Check,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  MoreHorizontal,
  Copy,
  Trash2,
  Edit3,
  Save,
  RotateCcw,
  Send,
  Sparkles,
  Bot,
  User,
  Code,
  AlertCircle,
  AlertTriangle,
  Info,
  Lightbulb,
  Layers,
  Puzzle,
  Command,
  ArrowUp,
  ArrowDown,
  RefreshCw,
  Eye,
  EyeOff,
  Maximize2,
  Minimize2,
  PanelLeftClose,
  PanelLeftOpen,
  type LucideProps,
} from "lucide-react";

const icons = {
  file: File,
  folder: Folder,
  "folder-open": FolderOpen,
  typescript: FileCode,
  javascript: FileCode,
  react: FileCode,
  python: FileCode,
  rust: FileCode,
  go: FileCode,
  json: FileJson,
  markdown: FileText,
  css: FileCode,
  sass: FileCode,
  html: FileCode,
  config: Settings,
  lock: File,
  git: GitBranch,
  image: Image,
  settings: Settings,
  "git-branch": GitBranch,
  search: Search,
  terminal: Terminal,
  chat: MessageSquare,
  play: Play,
  close: X,
  plus: Plus,
  minus: Minus,
  check: Check,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  more: MoreHorizontal,
  copy: Copy,
  trash: Trash2,
  edit: Edit3,
  save: Save,
  undo: RotateCcw,
  send: Send,
  sparkles: Sparkles,
  bot: Bot,
  user: User,
  code: Code,
  error: AlertCircle,
  warning: AlertTriangle,
  info: Info,
  suggestion: Lightbulb,
  layers: Layers,
  extensions: Puzzle,
  command: Command,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  refresh: RefreshCw,
  eye: Eye,
  "eye-off": EyeOff,
  maximize: Maximize2,
  minimize: Minimize2,
  "panel-close": PanelLeftClose,
  "panel-open": PanelLeftOpen,
};

export type IconName = keyof typeof icons;

interface IconProps extends LucideProps {
  name: IconName;
}

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = icons[name] || File;
  return <IconComponent {...props} />;
}
